name: Publish Javadoc

on:
  push:
    branches:
      - main
    paths:
      # 监视 Java 文件的更改，确保 Javadoc 在代码更改时生成
      - '**/*.java'
  workflow_dispatch:

jobs:
  publish-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v5

      - name: 设置 Java 环境 - 使用Oracle JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'oracle'
          architecture: x64
      - name: 缓存maven依赖
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 生成Javadoc
        run: |
          ./mvnw compile -P release
          ./mvnw --batch-mode javadoc:aggregate -P release -Dmaven.test.skip=true

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          publish_dir: target/reports/apidocs
          external_repository: lishangbu/orange-site
          publish_branch: main
          destination_dir: javadoc-api
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'