name: Publish DockerHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    # 使用矩阵策略并行构建多个服务,避免重复代码,提高构建效率
    strategy:
      matrix:
        service: [orange-admin-server]
    steps:
      - uses: actions/checkout@v5
      - name: 设置 Java 环境 - 使用Oracle JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'oracle'
          architecture: x64
      - name: 缓存maven依赖
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 提取maven版本
        id: projectVersion
        run: echo "version=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.5.1:evaluate -DforceStdout -Dexpression=revision -q)" >> $GITHUB_OUTPUT

      - name: Docker 登录
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像${{ github.event_name == 'pull_request' && ' (仅验证)' || ' 并推送' }}
        run: |
          ./mvnw -B compile
          ./mvnw -f orange-application/${{ matrix.service }}/pom.xml spring-boot:build-image
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "✅ 镜像构建验证完成: ${{ matrix.service }}"
          else
            docker push docker.io/${{secrets.DOCKER_USERNAME}}/${{ matrix.service }}:latest
            docker tag docker.io/${{secrets.DOCKER_USERNAME}}/${{ matrix.service }}:latest docker.io/${{secrets.DOCKER_USERNAME}}/${{ matrix.service }}:${{ steps.projectVersion.outputs.version }}
            docker push docker.io/${{secrets.DOCKER_USERNAME}}/${{ matrix.service }}:${{ steps.projectVersion.outputs.version }}
            echo "✅ 镜像构建并推送完成: ${{ matrix.service }}"
          fi
